/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f1e53107-1b0b-4279-88d8-acd2cba54a46",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_GlhCez5Q3",
    "aws_user_pools_web_client_id": "6t425f9auu78pfqq36csjktfi",
    "oauth": {}
};


export default awsmobile;
